app:
  name: SpringApplication
  version: 1.0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/internship
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  profiles:
    active: present
---
#Профиль dev
spring:
  config:
    activate:
      on-profile: dev
realise: 2.0
---
#Профиль present
spring:
  config:
    activate:
      on-profile: present
realise: 1.2
